### ISSUE TITLE
Possible issue CubeCalc addressing server credentials

### ISSUE THREAD

**Issue by tm1rules** [cubewise-code/cubecalc#11]
Hi,

I have previously been able to get CubeCalc working on my IBM Cloud environment using the sample provided, however it appears something may have changed with how CubeCalc.py addresses the credentials as the script now aborts when I attempt to run the sample IRR script.  It appears that CubeCalc now omits an import of Base64, although it still aborts even if I use the plain text password.

Example of script used;
python CubeCalc.py --method "IRR" --tm1_source "guardian-dev" --tm1_target "guardian-dev" --cube_source "Py Project Planning" --cube_target "Py Project Summary" --view_source "Project1" --view_target "Project1 IRR" --tidy False

Attached are the log file generated by CubeCalc and an example of how my Config.ini file appears.  Please let me know if you have any questions or require any further detail.

Regards,
Peter

[CubeCalc.log](https://github.com/cubewise-code/cubecalc/files/3175462/CubeCalc.log)

**Comment by tm1rules** [comment]
I can confirm that the above config.ini is working still with my previous version of CubeCalc using both Plain Text and Base64 encoded passwords.

**Comment by MariusWirtz** [comment]
Hi @tm1rules ,

sorry for this confusion. 
The reason it does not work is because the latest release of CubeCalc is based on the latest Release of TM1py.

Unfortunately at the moment you can download that latest release of TM1py **only** from Github. [here](https://github.com/cubewise-code/tm1py).

We plan to draft the new TM1py release this month. Then you would be able to download the recent version of TM1py through the classic way:

`pip install TM1py --upgrade`

Regarding the config.ini file. If you do upgrade and you store the password b64-encoded in it, you need to add one more line:
`decode_b64=True`

Cheers,

Marius

**Comment by tm1rules** [comment]
Thanks for the prompt reply Marius,  I attempted updating TM1py today by downloading the updated version from Github and updating the contents of the folder;
C:\ProgramData\Anaconda3\lib\site-packages\TM1py

However I am now receiving the following error, which I'm guessing could be an issue with dependencies not being addressed.

Traceback (most recent call last):
  File "CubeCalc.py", line 8, in <module>
    from TM1py import TM1Service
  File "C:\ProgramData\Anaconda3\lib\site-packages\TM1py\__init__.py", line 19, in <module>
    from TM1py.Services.ObjectService import ObjectService
  File "C:\ProgramData\Anaconda3\lib\site-packages\TM1py\Services\__init__.py", line 2, in <module>
    from TM1py.Services.RESTService import RESTService
  File "C:\ProgramData\Anaconda3\lib\site-packages\TM1py\Services\RESTService.py", line 8, in <module>
    from requests_negotiate_sspi import HttpNegotiateAuth
ModuleNotFoundError: No module named 'requests_negotiate_sspi'

I'll just wait until the `pip install tm1py --upgrade` has been updated with the latest TM1py version.  Thanks again for your assistance though.

Regards,
Peter

**Comment by MariusWirtz** [comment]
Just wanted to inform you that we upgraded TM1py and you can download the latest version through `pip`

Cheers,

Marius

**Comment by tm1rules** [comment]
Thanks for the update Marius, I will upgrade and re-test this.  Cheers, Peter
